modLoader="javafml"
loaderVersion="[32,)"
license="General Public License v3"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/cheat-mode/issues"

[[mods]]
    modId="cheatmode"
    version="${file.jarVersion}"
    displayName="Cheat Mode Mod"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/cheat-mode"
    #logoFile="cheatmode.png"
    authors="justAm0dd3r"
    description='''
A mod that makes it so you can access the creative inventory from the survival gamemode.
Allows players to test things out in survival.
'''

[[dependencies.cheatmode]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cheatmode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    ordering="NONE"
    side="BOTH"
