modLoader="javafml"
loaderVersion="[32,)"
license="General Public License v3"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/cheat-mode/issues"

[[mods]]
    modId="cheatmode"
    version="${version}"
    displayName="Cheat Mode Mod"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/cheat-mode"
    #logoFile="cheatmode.png"
    authors="justAm0dd3r"
    description='''
Access the creative inventory from survival, configure your reach, disable damage, etc.
For testing stuff out in survival.
Needs gamemode permissions to work correctly on servers!
    '''

[[dependencies.cheatmode]]
    modId="forge"
    mandatory=true
    versionRange="[43.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cheatmode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    ordering="NONE"
    side="BOTH"
